image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info
params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  BOSH_CA_CERT:
  ENV_TARGET_FILE:
run:
  path: cf-mysql-ci/ci/tasks/delete-deployment-no-env-metadata/task.sh

platform: linux
