platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info

params:
  MYSQL_TUNNEL_USERNAME:
  ENV_TARGET_FILE:
  SSH_KEY_FILE:

run:
  path: cf-mysql-ci/ci/tasks/verify-no-remote-access/task.sh

