platform: linux

image_resource: image_resource
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info
  - name: cf-mysql-release

params:
  ENV_TARGET_FILE: bosh-lite-info/director-url
  BOSH_CLIENT: REPLACE-ME
  BOSH_CLIENT_SECRET: REPLACE-ME
  BOSH_DEPLOYMENT: cf-mysql

run:
  path: cf-mysql-ci/ci/tasks/run-data-loss-tests/task.sh