image_resource:
  source:
    repository: cloudfoundry/cf-mysql-ci
  type: docker-image
inputs:
- name: cf-mysql-ci
- name: environment
params:
  BOSH_DEPLOYMENT:
  ENV_METADATA: environment/metadata
platform: linux
run:
  path: cf-mysql-ci/ci/tasks/delete-deployment/task.sh
