image_resource:
  source:
    repository: cloudfoundry/cf-mysql-ci
  type: docker-image
inputs:
- name: cf-mysql-ci
- name: deployments
params:
  DEPLOYMENTS_DIR: deployments
platform: linux
run:
  path: cf-mysql-ci/ci/tasks/destroy-bosh-lite-terraform/task.sh
