---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: bosh-lite-stemcell
- name: cf-mysql-ci
- name: gcp-bosh-stemcell

run:
  path: cf-mysql-ci/ci/tasks/gate-on-stemcells/task.sh

