platform: linux
image_resource: *image_resource
inputs:
- name: cf-mysql-ci
- name: bosh-lite-info
- name: deployments
  path: deployments-core-services
outputs:
- name: url
run:
  path: cf-mysql-ci/ci/tasks/create-dns/task.sh

