---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: bosh-lite-info
- name: deployments
  path: deployments-core-services

outputs:
- name: url

run:
  path: cf-mysql-ci/ci/tasks/create-dns/task.sh

