---
platform: linux

image_resource:
  source:
    repository: cloudfoundry/cf-mysql-ci
  type: docker-image

inputs:
- name: bbl-github-release
  optional: true
- name: bosh-cli-github-release
  optional: true
- name: credhub-cli-github-release
  optional: true
- name: terraform-github-release
  optional: true
- name: cf-mysql-ci

outputs:
- name: docker-build-args

run:
  path: cf-mysql-ci/ci/tasks/generate-docker-build-args-file/task.sh

