---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info
  - name: cf-mysql-deployment

params:
  BOSH_CA_CERT_PATH: bosh-lite-info/ca-cert
  BOSH_CLIENT: ((core-services-ci-credentials/Notes/bosh-lite-username))
  BOSH_CLIENT_SECRET: ((core-services-ci-credentials/Notes/bosh-lite-password))
  BOSH_DEPLOYMENT: cf-mysql
  ENV_TARGET_FILE: bosh-lite-info/director-url
  ENABLE_REMOTE_ADMIN_ACCESS: true

run:
  path: cf-mysql-ci/ci/tasks/test-scaling/task.sh

