---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info
  - name: cf-mysql-deployment

params:
  BOSH_CA_CERT_PATH:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  ENV_TARGET_FILE:
  ENABLE_REMOTE_ADMIN_ACCESS:
  SCALE_TO_FULL_TEST: false

run:
  path: cf-mysql-ci/ci/tasks/test-scaling/task.sh

