---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: release-tarball
- name: gcp-bosh-stemcell

outputs:
- name: compiled-release-tarball

params:
  BOSH_ALL_PROXY:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_JUMPBOX_PRIVATE_KEY:
  RELEASE_NAME:
  STEMCELL_LINE:
  OUTPUT_DIR: compiled-release-tarball

run:
  path: cf-mysql-ci/scripts/compile_release
