---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-release
- name: cf-mysql-ci

outputs:
- name: cf-mysql-release-changed

params:
  GIT_AUTHOR_NAME: Concourse CI
  GIT_AUTHOR_EMAIL: pivotal-core-services-eng@pivotal.io
  BLOBS_BUCKET_NAME: ~
  AWS_ACCESS_KEY_ID: ~
  AWS_SECRET_ACCESS_KEY: ~

run:
  path: cf-mysql-ci/scripts/update-acceptance-tests/build-and-upload-cipher-finder-jar.sh


