---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3.1'

inputs:
- name: cf-mysql-ci
- name: cf-mysql-release

run:
  path: cf-mysql-ci/ci/tasks/test-broker-dependencies/task.sh

