platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3.1'

inputs:
- name: cf-mysql-release

run:
  path: bash
  args:
  - -c
  - |
    set -eux

    gem install bundler-audit
    bundle-audit update

    cd cf-mysql-release/src/cf-mysql-broker

    bundle-audit

