---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: bosh-lite-info
- name: url
- name: deployments
  path: deployments-core-services
run:
  path: cf-mysql-ci/ci/tasks/delete-dns/task.sh


