---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: deployments
- name: bosh-lite-info

outputs:
- name: bosh-lite-info-stemcell-deleted

run:
  path: cf-mysql-ci/ci/tasks/delete-stemcell/task.sh

