---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
- name: cf-mysql-ci
- name: deployments

outputs:
- name: deployments-terraformed

params:
  OUTPUT_DIR: deployments-terraformed
  DEPLOYMENTS_DIR: deployments

run:
  path: cf-mysql-ci/ci/tasks/apply-bosh-lite-terraform/task.sh

