---
platform: linux

image_resource:
  source:
    repository: cloudfoundry/cf-mysql-ci
  type: docker-image

inputs:
- name: cf-mysql-ci
- name: commit-message
- name: github-release

outputs:
- name: github-release-committed

params:
  GIT_COMMIT_MESSAGE:

run:
  path: cf-mysql-ci/ci/tasks/commit-github-release-changes/task.sh
