---
platform: linux

image_resource:
  source:
    repository: cloudfoundry/cf-mysql-ci
  type: docker-image

inputs:
- name: cf-mysql-ci
- name: github-release
- name: commit-message
outputs:
- name: github-release-committed
params:
  GIT_COMMIT_MESSAGE:
  REPO_DIR:
  OUTPUT_DIR:
run:
  path: cf-mysql-ci/ci/tasks/commit-github-release-changes/task.sh
