---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci
inputs:
  - name: bosh-lite-info
  - name: cf-mysql-ci
run:
  path: cf-mysql-ci/ci/tasks/test-galera-encryption/task.sh
