platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info

params:
  ENV_TARGET_FILE:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:

run:
  path: cf-mysql-ci/ci/tasks/restart-broken-node-after-data-loss/task.sh

