
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: bosh-lite-info
  - name: mysql-load-test-release

params:
  BOSH_CA_CERT_PATH: bosh-lite-info/ca-cert
  BOSH_CLIENT: REPLACE-ME
  BOSH_CLIENT_SECRET: REPLACE-ME
  ENV_TARGET_FILE: bosh-lite-info/director-url
  ENV_METADATA:
  BOSH_DEPLOYMENT:
  RELEASE_DIR:
run:
  path: cf-mysql-ci/ci/tasks/create-load-test-deployment/task.sh

