---
platform: linux
image_resource: &image_resource
  type: docker-image
  source:
    repository: cloudfoundry/cf-mysql-ci

inputs:
  - name: cf-mysql-ci
  - name: cloud-config
  - name: bosh-lite-info

params:
  CLOUD_CONFIG:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  ENV_TARGET_FILE: bosh-lite-info/director-url
  BOSH_CA_CERT_PATH: bosh-lite-info/ca-cert

run:
  path: cf-mysql-ci/scripts/bosh-lite-gcp/update-cloud-config
