---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalcf/mysql-restore
inputs:
- name: bosh-lite-info
- name: cf-mysql-ci
params:
  MYSQL_TUNNEL_USERNAME:
  MYSQL_VM_IP:
  ENV_TARGET_FILE:
  SSH_KEY_FILE:
run:
  path: cf-mysql-ci/ci/tasks/persistence-load-test-data/task.sh

